// <auto-generated />
namespace BangazonOrientation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addNullableFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNullableFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201805090131323_addNullableFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
